# -*- mode: ruby -*-
# vi: set ft=ruby :

#unless Vagrant.has_plugin?("vagrant-docker-compose")
#  system("vagrant plugin install vagrant-docker-compose")
#  puts "Dependencies installed, please try the command again."
#  exit
#end

Vagrant.configure("2") do |config|
  if File.exist? ".vagrant/machines/default/virtualbox/creator_uid"
        File.delete ".vagrant/machines/default/virtualbox/creator_uid"
  end
#  if Vagrant::Util::Platform.windows?
#  elsif Vagrant::Util::Platform.linux?
#  end

  config.vm.box = "debian/jessie64"
  config.vm.box_check_update = false

  config.vm.hostname = 'webserver'
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.network "private_network", ip: "192.168.33.10"

  # config.vm.network "public_network"

  # config.vm.synced_folder "./web", "/home/web", create: true

  config.vm.provider "virtualbox" do |vb|
    vb.name = 'webserver'
    vb.memory = "1024"
    vb.cpus = '1'
  end

  config.vm.provision "shell", path: "bootstrap.sh"

  config.vm.provision "docker"
  config.vm.provision "docker_compose", yml: '/home/roger/vagrant-data/webserver/docker-compose.yml'
#  config.vm.provision "docker" do |d|
#    d.run "web",
#      image: "eboraas/apache",
#      args: "-v 'web/www:/var/www'"
#  end
end
